=head1 NAME

fabsys_backup-kill - Forcibly kill a running backup run

=head1 SYNOPSIS

B<fabsys backup-kill> <I<brun_id>> [B<--note> <I<note>>]

=head1 DESCRIPTION

The B<fabsys backup-kill> causes a running backup run to abort, and immediately
be considered "failed". This can be useful if a backup run was accidentally
started, or if a run is malfunctioning or hanging for some reason.

Note that killing a backup run does not immediately kill in-progress volume
dump processes, or other in-parallel aspects of a backup run. However, all
aspects of a backup run should notice fairly quickly that a backup run has
failed (after a few minutes at most), and will abort themselves.

=head1 OPTIONS

=over 4

=item <I<brun_id>>

The backup run id to kill. Backup run ids can be shown with the
C<fabsys_backup-status(1)> command.

=item B<--note> <I<note>>

This flag specifies a free-form note to indicate why the backup run is being
killed.

=back

=head1 PRIVILEGED REQUIRED

The issuer of this command must be able to read the FABS configuration
(specifically, the database access information), typically in
B</etc/fabs/fabs.yaml.d/>.

=head1 COPYRIGHT

Copyright (c) 2015, Sine Nomine Associates.

See the provided LICENSE file for licensing terms.
